### ISSUE TITLE
Failing check when I want an informative check

### ISSUE THREAD

**Issue by kaihendry** [lycheeverse/lychee-action#37]
I use this action simply:

```
name: Links

on:
  workflow_dispatch:
  push:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress **/*.mdwn
``` 
upon https://github.com/kaihendry/geekout.org.uk/blob/07328724ab98e8fc91105255654b399baa27fe58/.github/workflows/links.yaml

However it has two surprisingly issues:

* it causes a failure, I assumed reading the documentation I needed `run: exit ${{ steps.lychee.outputs.exit_code }}` to actually cause a failure
* doesn't appear to summarize the failing links in a sane way

What am I doing wrong please?

**Comment by mre** [comment]
Thanks for trying lychee. 😊 

About your questions:
* You are right that the documentation mentioned the explicit propagation of the exit code. This caused some confusion in the past, so we changed it (see https://github.com/lycheeverse/lychee-action/issues/20). The exit code now gets passed unconditionally to the next step. I've updated the docs. To restore the old behavior, you can use [`continue-on-error`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error) on the job level:

  ```yaml
  name: Links
  
  on:
    workflow_dispatch:
    push:
  
  jobs:
    linkChecker:
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
        - uses: actions/checkout@v2
        - name: Link Checker
          uses: lycheeverse/lychee-action@v1
          with:
            args: --verbose --no-progress **/*.mdwn
  ```
  
  See also https://qmacro.org/autodidactics/2020/07/21/continue-on-error/.

* The summary gets written to`./lychee/out.md` by default (see https://github.com/lycheeverse/lychee/blob/6ef121d3eb9a778b073e99732544caade2e40c03/lychee-bin/src/main.rs#L241-L243 and https://github.com/lycheeverse/lychee-action/blob/805f3b2e03e0b517045fbd2f09c21f39fa33df44/entrypoint.sh#L12). (The reason why you don't see the rest of the output is that it gets printed to `stdout` directly (ref: https://github.com/lycheeverse/lychee/blob/6ef121d3eb9a778b073e99732544caade2e40c03/lychee-bin/src/main.rs#L142-L145) The idea is that a subsequent step can use this output to create an issue in case of errors. We could bundle the issue creation into the action and provide a flag to bypass the redirection if needed. Something like

  ```yaml
  - name: Link Checker
    uses: lycheeverse/lychee-action@v1
    with:
      args: --verbose --no-progress **/*.mdwn
      issue: false
  ```

**Comment by kaihendry** [comment]
Thanks, I applied your change https://github.com/kaihendry/geekout.org.uk/runs/3034419141

Is there a way just to highlight the failing links? I.e. do not show the successful / working links

![image](https://user-images.githubusercontent.com/765871/125151323-25b6e380-e178-11eb-8b58-3ee17898cd4d.png)

This would help me prioritize what I should fix first.

And last but not least, is there a sane way to "fix" broken links? Propose to rewrite them to http://web.archive.org/ or https://archive.is/ if the URL is archived upon them?

Thank you again!

**Comment by mre** [comment]
> Is there a way just to highlight the failing links?

Sure, just remove `--verbose`.

> And last but not least, is there a sane way to "fix" broken links? Propose to rewrite them to http://web.archive.org/ or https://archive.is/ if the URL is archived upon them?

I thought this was proposed before, but I can't find the issue anymore. 🤔 It's a great idea, though. We could add a `--fix` flag that proposes those changes. Could you create a new issue over at https://github.com/lycheeverse/lychee to track that?

**Comment by mre** [comment]
Thanks for creating that ticket @kaihendry.

**Comment by kaihendry** [comment]
Hi, despite adding `continue-on-error: true`, I still see:

```
[Links/linkChecker]   ❌  Failure - Link Checker
Error: exit with `FAILURE`: 2
```

Is that expected? I rather just have it run and not look like some sort of CI fail, if that makes any sense.

Thank you!

**Comment by mre** [comment]
I think that's expected, yeah. `continue-on-error: true` just means that an error will not cancel the entire pipeline. However individual steps can still fail.

**Comment by mre** [comment]
I haven't tested it, but perhaps you could overwrite the lychee exit code?

```yaml
- name: Link Checker
  uses: lycheeverse/lychee-action@v1
  with:
    args: --verbose --no-progress **/*.mdwn || exit 0
    issue: false
```

**Comment by kaihendry** [comment]
Looks like the pipe gets quoted.... hmm https://github.com/kaihendry/geekout.org.uk/runs/3067535049?check_suite_focus=true

**Comment by mre** [comment]
We could add an `exit` field to the action like so:

```yaml
- name: Link Checker
  uses: lycheeverse/lychee-action@v1
  with:
    args: --verbose --no-progress **/*.mdwn
    issue: false
    exit: 0
 ```
 
 Alternatively we could add a flag to lychee:

```yaml
- name: Link Checker
  uses: lycheeverse/lychee-action@v1
  with:
    args: --verbose --no-progress **/*.mdwn --exit 0
    issue: false
```

To be honest, these options feel like hacks to me. I wonder if that's a common enough use-case to add that feature. 😕

**Comment by kaihendry** [comment]
`continue-on-error` in the step works actually, thanks for you help !!

https://github.com/kaihendry/geekout.org.uk/actions/runs/1030628076
